# Funding
# https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

github: rothiotome
ko_fi: rothiotome
custom: ["https://www.twitch.tv/rothiotome/", "https://rothiotome.itch.io/"]